server:
  port: 8081
spring:
  application:
    name: libary
# Database configuration    
  datasource:
    url: jdbc:h2:mem:libary
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.HSQLDialect
# https://www.h2database.com/html/features.html#in_memory_databases      
  flyway:
    url: jdbc:h2:mem:libary;DB_CLOSE_DELAY=-1
    schemas: PUBLIC
    user: sa
    password: 
logging:
   level:
      com:
         lexmatos:
            library: 
               domain: DEBUG 
